name: Jeremy Yang
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-octicons
  - jekyll-github-metadata
sass:
  sass_dir: _sass
  style: compressed
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
